name: Tests

on:
  pull_request:

jobs:
  test:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test project
        run: python -m unittest discover -t src/ -s src/tests/unit
